### ISSUE TITLE
Rlink2 Upgrade from V3 to V9 and get the issue

### ISSUE THREAD

**Issue by Goran-Barznje** [cedricp/ddt4all#593]
Once i upgraded from V3 to V9 i lost many things of my R- link 2 screen, so now i want to downgrade from V9 to V3

Much appreciated for your help image![image](https://user-images.githubusercontent.com/82806656/125495725-06d7997b-d1d1-4dca-af9f-d964a8b6462f.jpeg)![image](https://user-images.githubusercontent.com/82806656/125495766-3efdf967-2c92-4573-b59c-a0710808dc3e.jpeg)

**Comment by AlMeu** [comment]
The upgrade from v2.2 or v3.3 to v7.0 is done only at Renault dealers.
Now you are lucky because is not blocked, but a smal distance to block anyway if you try downgrade.
If I have it on my test desk, I could try, but is very risky.

**Comment by Goran-Barznje** [comment]
The issue is there is no dealer available in my country to downgrade it

Can you please help to fix that by myself?

Thanks

**Comment by AlMeu** [comment]
An email?

**Comment by Goran-Barznje** [comment]
> The upgrade from v2.2 or v3.3 to v7.0 is done only at Renault dealers.
> 
> Now you are lucky because is not blocked, but a smal distance to block anyway if you try downgrade.
> 
> If I have it on my test desk, I could try, but is very risky. 
> 
> 

Goran909090@gmail.com

**Comment by mfarramadan** [comment]
I want to downgrade from 3.3 to 2.2... is there a way to do so ?

**Comment by AlMeu** [comment]
Why you want do that?

**Comment by Vahidpa** [comment]
Hi all,unfortunately i have same problem too,but i update it from v3 to v9 directly 
Head unit working now,but many thing don't working, how can i back to v3?
Please help me
@AlMeu

**Comment by AlMeu** [comment]
It work luckly, but with many problems.
I think remains you replace the unit.
An email?

**Comment by Vahidpa** [comment]
@AlMeu vahidp@gmail.com

**Comment by sajadkhanizade64** [comment]
I have same problam.any solution?

**Comment by Vahidpa** [comment]
> I have same problam.any solution?

email me please
my email is vahidp@gmail.com

**Comment by AlMeu** [comment]
Unfortunately the solution for you is to replace the unit.

**Comment by sajadkhanizade64** [comment]
> [sajadkhanizade64](https://github.com/sajadkhanizade64) Unfortunately the solution for you is to replace the unit.

No.i fixed this pb before in 2y ago.but again i upgrade again...:)))

**Comment by AlMeu** [comment]
We have an old proverb:
"The pitcher doesn't go to the water often" :-)

**Comment by sajadkhanizade64** [comment]
> We have an old proverb: "The pitcher doesn't go to the water often" :-)

Lol:)) i upgrade from v3 to v9.then downgrde to 3 and fix park sensor and camera.but no sound.i had sound on v9:)) i reset ecu and all sounds gone.

**Comment by AlMeu** [comment]
It's exactly what I mean, all the time there will be a problem.
Wasting time and nervs for nothing.
Better change it and all problems remains behind.

**Comment by sajadkhanizade64** [comment]
@shrlnm hi.i used macro for sound and git this error.can u help me?
![Uploading 20220418_123854.jpg…]()

**Comment by sajadkhanizade64** [comment]
![Uploading 20220418_123854.jpg…]()

**Comment by sajadkhanizade64** [comment]
![Uploading 20220418_123854.jpg…]()

**Comment by sajadkhanizade64** [comment]
![Uploading 20220418_123854.jpg…]()

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
